name: Bug Report
description: Report a defect or regression in AKKO.
title: "[Bug] Short summary"
labels:
  - bug
assignees: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Bug classification
      options:
        - Functional bug
        - Regression
        - Performance issue
        - Security concern
        - UI/UX defect
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a concise overview of the bug and its impact.
      placeholder: What went wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Detail the exact steps to reproduce the issue.
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: Describe what actually happened, including error messages.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide OS, Python version, AKKO version, browser (if applicable), and other configuration details.
      placeholder: "Example: macOS 14.1, Python 3.11, AKKO commit abc123"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and diagnostics
      description: Include stack traces, console output, or screenshots as needed.
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: If a temporary workaround exists, document it here.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Link related issues, PRs, or notes.
