name: Credentials Issue
description: Report problems or requests related to credential storage, encryption, or syncing.
title: "[Credentials] Short summary"
labels:
  - area:credentials
assignees: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Issue type
      options:
        - Bug
        - Feature
        - Enhancement
        - Documentation
        - Question
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Give a concise description of the credential issue or request.
      placeholder: 'Example: "Encrypted credentials fail to decrypt in prod"'
    validations:
      required: true
  - type: textarea
    id: flow
    attributes:
      label: Impacted credential flow
      description: Specify the action that fails or needs improvement (import, edit, rotation, sync, etc.).
  - type: textarea
    id: scope
    attributes:
      label: Affected scope
      description: List the users, environments, and credential sets involved.
      placeholder: 'Example: "Admin accounts in staging"'
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce / Implementation outline
      description: Provide steps to reproduce or outline the change needed.
      placeholder: |
        1. Run …
        2. Open …
        3. Observe …
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: Describe the desired behaviour.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result / Error details
      description: Include error messages, stack traces, or mismatched behaviour.
    validations:
      required: true
  - type: textarea
    id: data
    attributes:
      label: Data or fixtures
      description: Reference relevant entries (anonymised) from `data/` or other sources.
      placeholder: 'Example: "public/private: entry id 42"'
  - type: textarea
    id: environment
    attributes:
      label: Environment details
      description: OS, Python runtime, AKKO version, encryption settings, and any feature flags.
    validations:
      required: true
  - type: textarea
    id: security
    attributes:
      label: Security considerations
      description: Note any security implications, data exposure, or compliance requirements.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Related issues, PRs, logs, or metrics.
