name: Frontend Issue
description: Report UI or UX bugs, layout regressions, or request new frontend behaviour.
title: "[Frontend] Short summary"
labels:
  - area:frontend
assignees: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Issue type
      options:
        - Bug
        - Feature
        - Enhancement
        - Design
        - Documentation
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: State the frontend problem or request in one or two sentences.
      placeholder: 'Example: "Credential list page breaks on mobile"'
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Page or component
      description: Identify the page, route, or shared component that is impacted.
      placeholder: 'Example: "/credentials/manage" form'
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce / Desired interaction
      description: Provide reproduction steps for bugs or describe the desired flow for new features.
      placeholder: |
        1. Navigate to …
        2. Perform …
        3. Observe …
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Describe what should happen from the user's perspective.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour / Screenshot
      description: Detail what actually happens; add screenshots or screen recordings when possible.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment details
      description: Browser, version, viewport size, OS, and AKKO build hash if available.
      placeholder: 'Example: "Safari 17.1, 1440x900, macOS 14.1"'
    validations:
      required: true
  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility impact
      description: Note any accessibility concerns (keyboard navigation, contrast, screen reader behaviour, etc.).
  - type: textarea
    id: assets
    attributes:
      label: Assets and references
      description: Attach designs, Figma links, logs, or related issues/PRs.
